### PR TITLE
IWF-533: Fix locking_test.go Integration Test

### LINKED ISSUE #536: Fix locking_test.go Integration Test
The locking integration test has been failing for a while, but somehow the pipelines weren't failing:

This test needs to be fixed.

1. It seems that the 4 Signals emitted at the start are being lost when the Workflow is being reset: https://github.com/indeedeng/iwf/actions/runs/12913194642/job/36013969433#step:4:4287
2. And under some circumstances the internal channel size is also not matching as expected: https://github.com/indeedeng/iwf/actions/runs/12913194673/job/36009847771#step:4:2649

### PR DESCRIPTION
**Pull request by samuel27m**
### Checklist
- [x] Code compiles correctly
- [x] Tests for the changes have been added
- [x] All tests passing
- [x] **This PR change is backwards-compatible**
- [ ] **This PR CONTAINS a (planned) breaking change** (it is not backwards compatible)

### Related Issue
Closes #536

### CODE REVIEW

**Comment by lwolczynski** [comment]
🙌

**Review by lwolczynski — APPROVED** [review]

File: integ/locking_test.go [hunk 1]
```diff
@@ -270,8 +264,10 @@ func doTestLockingWorkflow(t *testing.T, backendType service.BackendType, config
 	//reset here with reapply and compare counter
 	resetReq := apiClient.DefaultApi.ApiV1WorkflowResetPost(context.Background())
 	_, httpResp, err = resetReq.WorkflowResetRequest(iwfidl.WorkflowResetRequest{
-		WorkflowId: wfId,
-		ResetType:  iwfidl.BEGINNING,
+		WorkflowId:        wfId,
+		ResetType:         iwfidl.STATE_ID,
+		StateId:           ptr.Any("StateWaiting"),
```
Comment (lwolczynski) [inline integ/locking_test.go:269]: Q: Is this change needed? I think the test should pass even if the workflow is reset from the beginning?
