### PR TITLE
IWF-343: Fix concurrent write panic for parallel test

### LINKED ISSUE #472: Fix concurrent write panic for parallel test
Maybe using sync.Map: https://medium.com/@luanrubensf/concurrent-map-access-in-go-a6a733c5ffd1

### PR DESCRIPTION
**Pull request by samuel27m**
### Checklist
- [x] Code compiles correctly
- [ ] Tests for the changes have been added
- [x] All tests passing
- [x] **This PR change is backwards-compatible**
- [ ] **This PR CONTAINS a (planned) breaking change** (it is not backwards compatible)

### Related Issue
Closes #472

### CODE REVIEW

File: integ/workflow/parallel/routers.go [hunk 1]
```diff
@@ -71,7 +72,11 @@ func (h *handler) ApiV1WorkflowStateStart(c *gin.Context, t *testing.T) {
 	log.Println("received state start request, ", req)
 
 	if req.GetWorkflowType() == WorkflowType {
-		h.invokeHistory[req.GetWorkflowStateId()+"_start"]++
+		if value, ok := h.invokeHistory.Load(req.GetWorkflowStateId() + "_start"); ok {
+			h.invokeHistory.Store(req.GetWorkflowStateId()+"_start", value.(int64)+1)
+		} else {
+			h.invokeHistory.Store(req.GetWorkflowStateId()+"_start", int64(1))
+		}
```
Comment (samuel27m) [inline integ/workflow/parallel/routers.go:79]: I couldn't reproduce the issue described, but I can see that this issue could very well happen due to the nature of the Workflow in this test.

Looking for opinions on if this is something that we need to polish a bit more, and make all our other tests also use `sync.Map` for storing the current `invokeHistory` in the integration tests

Comment (samuel27m) [reply integ/workflow/parallel/routers.go:79]: As discussed, I have applied the same logic now for all the tests. i.e. all tests now use `sync.Map` which can be written to concurrently

File: integ/any_command_combination_test.go [hunk 2]
```diff
@@ -10,7 +10,7 @@ import (
 	"time"
 
 	"github.com/indeedeng/iwf/gen/iwfidl"
-	anycommandconbination "github.com/indeedeng/iwf/integ/workflow/any_command_combination"
+	anycommandcombination "github.com/indeedeng/iwf/integ/workflow/any_command_combination"
```
Comment (samuel27m) [inline integ/any_command_combination_test.go:13]: This was just a typo that I noticed while working on the tests
